name: 'Git-knowledge Json Action'
description: 'Creates a git-knowledge json file'
inputs:
  repo-token:
    description: 'GitHub Token'
    required: true
    default: ''
  repo-list-path:
    description: 'Path to a file with list of repos to include'
    required: true
    default: 'repos.txt'
  knowledge-json-path:
    description: 'Path to knowledge output file'
    required: true
    default: 'src/assets/knowledge.json'
runs:
  using: 'node12'
  main: 'index.js'
