on: [push]

jobs:
  extract-notes-tags:
    runs-on: ubuntu-latest
    name: Extract tags from notes
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Extract tags from notes repos
        uses: digitalreplica/hello-world-javascript-action@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          repo-list-path: 'repos.txt'
          knowledge-json-path: 'knowledge.json'
      - name: List files in the repository
        run: |
          ls -l ${{ github.workspace }}
